spring:
  application:
    name: database_per_tenant
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

multitenancy:
  datasource-cache:
    maximumSize: 100
    expireAfterAccess: 10
  master:
    repository:
      packages: com.imbuka.database_per_tenant.multi_tenancy.repository;
    entityManager:
      packages: com.imbuka.database_per_tenant.multi_tenancy.domain
    datasource:
      url: jdbc:postgresql://localhost:5432/database_per_tenant
      username: imbuka
      password: postgres2549
    liquibase:
      enabled: false
  tenant:
    repository:
      packages: com.imbuka.database_per_tenant.repository
    entityManager:
      packages: com.imbuka.database_per_tenant.domain
    datasource:
      url-prefix: jdbc:postgresql://localhost:5432/
      hikari:
        maximumPoolSize: 2
        minimumIdle: 0
        idleTimeout: 30000
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml

encryption:
  secret: verySecret
  salt: jozo

server:
  port: 8080



